name: webapp_env
channels:
  - conda-forge
  - defaults
dependencies:

  - rdkit

  - pip:

    - captum

    - flask

    - gunicorn

    - ipython

    - numpy

    - pytorch-lightning

    - scikit-learn

    - https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp38-cp38-win_amd64.whl

    - matplotlib


