name: env
channels:
- conda-forge
- defaults
dependencies:
  
- matplotlib

- python

- rdkit

- flask

- gunicorn

- ipython

- numpy

- pytorch-lightning

- scikit-learn

- pip

- pip:

  - https://download.pytorch.org/whl/cpu/torch-1.5.1%2Bcpu-cp36-cp36m-linux_x86_64.whl
 
  - captum