name: webapp_env
channels:
  - conda-forge
  - defaults
dependencies:

  - rdkit

  - pip:

    - captum

    - flask

    - gunicorn

    - ipython

    - numpy

    - pytorch-lightning

    - scikit-learn

    - http://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp37-cp37m-linux_x86_64.whl

    - matplotlib


