name: webapp_env
channels:
  - conda-forge
  - defaults
dependencies:

  - rdkit

  - pip:

    - captum==0.3.1

    - flask==1.1.2

    - gunicorn==20.0.4

    - ipython==7.16.1

    - numpy==1.19.5

    - pytorch-lightning

    - scikit-learn==0.24.1

    - https://download.pytorch.org/whl/cpu/torch-1.3.1%2Bcpu-cp36-cp36m-linux_x86_64.whl

    - matplotlib
