name: webapp_env
channels:
  - conda-forge
  - defaults
dependencies:

  - rdkit

  - pip:

    - captum

    - flask

    - gunicorn

    - ipython

    - numpy

    - pytorch-lightning

    - scikit-learn

    - https://download.pytorch.org/whl/cpu/torch-1.3.1%2Bcpu-cp36-cp36m-linux_x86_64.whl

    - matplotlib


