name: env
channels:
- conda-forge
- defaults
dependencies:
  
- nomkl

- matplotlib-base=3.3.2

- python=3.6.12

- rdkit=2020.09.4

- pip

- captum==0.3.1

- flask==1.1.2

- gunicorn==20.0.4

- ipython==7.16.1

- numpy==1.19.5

- pytorch-lightning==1.1.5

- scikit-learn==0.24.1

- https://download.pytorch.org/whl/cpu/torch-1.5.1%2Bcpu-cp36-cp36m-linux_x86_64.whl
